Repository CruGlobal/godtools-swift, pull requests merged in 2022-08, with the labels that each got.

#1289 GT-1641 Add filter[system]=GodTools to mobile content resources api
  godtools/App/Share/Data/ResourcesRepository/Api/MobileContentResourcesApi.swift
Labels: Cru - Ready for Review

#1287 GT-1605 Accordion Analytics
  Podfile.lock
  godtools/App/Services/Renderer/Views/MobileContent/ViewFactory/MobileContentPageViewFactory.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionViewModel.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionViewModelType.swift
Labels: Cru - Ready for Review

#1286 GT-1733 divide by 0 check
  Podfile.lock
  godtools/App/Services/Renderer/Views/MobileContent/ViewFactory/MobileContentPageViewFactory.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionViewModel.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionViewModelType.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAnimation/MobileContentAnimationView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentStack/MobileContentStackView.swift
  godtools/App/Share/Views/AnimatedView/AnimatedViewModel.swift
  godtools/App/Share/Views/AnimatedView/AnimatedViewModelType.swift
Labels: Cru - Ready for Review

#1291 GT-1735 remove mock view models 2
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardNavButtonView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardVerticalTextView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/MockToolCardViewModel.swift
  godtools/App/Share/Domain/ViewModels/LessonCardProvider.swift
  godtools/App/Share/Domain/ViewModels/ToolCardProvider.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/LessonCardView.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/MockLessonCardViewModel.swift
Labels: Cru - Ready for Review

#1294 GT-1751 analytics fixes
  godtools/App/Features/Lessons/Lessons/LessonsContentViewModel.swift
  godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Services/Analytics/AnalyticsConstants.swift
Labels: Cru - Ready for Review

#1295 GT-1749 attachments repo for resource cards
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Lessons/Lessons/LessonsContentView.swift
  godtools/App/Features/Lessons/Lessons/LessonsContentViewModel.swift
  godtools/App/Features/Lessons/Lessons/LessonsListView/LessonsListView.swift
  godtools/App/Features/Lessons/Lessons/LessonsListView/LessonsListViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardNavButtonView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardVerticalTextView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/ToolSpotlightView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/ViewModels/ToolSpotlightViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/FavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/Subviews/NoFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/FavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModel.swift
  godtools/App/Features/Tools/Views/Tool/ToolItemInitialDownloadProgress.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Services/Attachments/DeviceAttachmentBanners.swift
  godtools/App/Share/Domain/UseCases/GetBannerImageUseCase/GetBannerImageUseCase.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/LessonCardView.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/LessonCardViewModel.swift
  godtools/App/Share/SwiftUI Views/LessonCardsView/LessonCardsView.swift
  godtools/App/Share/SwiftUI Views/ResourceCard Subviews/ResourceCardBannerImageView.swift
  godtools/App/Share/SwiftUI Views/ToolCardsCarouselView/ToolCardsCarouselView.swift
Labels: Cru - Ready for Review

#1299 GT-1448 remove old translations downloader and filecache
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/Features/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardView.swift
  godtools/App/Features/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardViewModel.swift
  godtools/App/Features/ToolDetails/ToolDetailsView.swift
  godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Services/Attachments/AttachmentsDownloader.swift
  godtools/App/Services/Attachments/AttachmentsFileCache.swift
  godtools/App/Services/InitialDataDownloader/InitialDataDownloader.swift
  godtools/App/Services/InitialDataDownloader/InitialDataDownloaderResourcesSync.swift
  godtools/App/Services/InitialDataDownloader/InitialDeviceResourcesLoader.swift
  godtools/App/Services/Renderer/Renderer/MobileContentRendererPageViewFactories.swift
  godtools/App/Services/Renderer/Views/Tool/ViewFactory/ToolPageViewFactory.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Header/ToolPageHeaderViewModel.swift
  godtools/App/Services/Renderer/Views/Training/ViewFactory/TrainingViewFactory.swift
  godtools/App/Services/Renderer/Views/Training/Views/TrainingTip/TrainingTipViewModel.swift
  godtools/App/Services/Resources/ResourcesApi/ResourcesApi.swift
  godtools/App/Services/Resources/ResourcesApi/ResourcesApiType.swift
  godtools/App/Services/Resources/ResourcesCleanUp/ResourcesCleanUp.swift
  godtools/App/Services/Resources/ResourcesCleanUp/ResourcesCleanUpError.swift
  godtools/App/Services/Resources/ResourcesDownloader.swift
  godtools/App/Services/TranslationsDownloader/TranslationDownloader.swift
  godtools/App/Services/TranslationsRepository/FileCache/TranslationsFileCache.swift
  godtools/App/Share/Data/ResourceBannerImageRepository/BundleResourceBannerImages.swift
  godtools/App/Share/Data/ResourceBannerImageRepository/ResourceBannerImageRepository.swift
  godtools/App/Share/Data/ResourcesSHA256FileCache/ResourcesSHA256FileCache.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsUseCase/GetAllFavoritedToolsUseCase.swift
Labels: Cru - Ready for Review

#1298 GT-1753 remove favorited resources cache from tool cards
  godtools.xcodeproj/project.pbxproj
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardNavButtonView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardVerticalTextView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/ToolSpotlightView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/ViewModels/ToolSpotlightViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/FavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/Subviews/NoFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/FavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Share/Domain/UseCases/ToggleToolFavoritedUseCase/ToggleToolFavoritedUseCase.swift
  godtools/App/Share/SwiftUI Views/ToolCardsCarouselView/ToolCardsCarouselView.swift
Labels: Cru - Ready for Review

#1301 GT-1760 filter out hidden tool variants for tool details
  godtools/App/Features/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardView.swift
  godtools/App/Share/Domain/UseCases/GetToolVersionsUseCase/GetToolVersionsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolVersionsUseCase/ToolVersionDomainModel.swift
Labels: Cru - Ready for Review

#1303 GT keep translations in database
  godtools/App/Share/Data/LanguagesRepository/Api/Models/LanguageModel.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/Sync/RealmResourcesCacheSync.swift
Labels: Cru - Ready for Review

#1304 GT-1728 Remove ConfigType protocol
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDelegate.swift
  godtools/App/AppDiContainer.swift
  godtools/App/Features/Menu/Menu/MenuViewModel.swift
  godtools/App/Flows/Menu/MenuFlow.swift
  godtools/App/Services/Analytics/Firebase/FirebaseAnalytics.swift
  godtools/App/Services/Analytics/Google/GoogleAdwordsAnalytics.swift
  godtools/App/Services/Analytics/Snowplow/SnowplowAnalytics.swift
  godtools/App/Services/AppConfig/ConfigType.swift
  godtools/App/Services/AppsFlyer/AppsFlyer.swift
  godtools/App/Services/FirebaseConfiguration/FirebaseConfiguration.swift
  godtools/App/Services/FollowUps/FollowUpsApi.swift
  godtools/App/Services/FollowUps/FollowUpsService.swift
  godtools/App/Services/GlobalActivity/GlobalActivityAnalyticsApi.swift
  godtools/App/Services/GlobalActivity/GlobalActivityServices.swift
  godtools/App/Services/TractRemoteShare/TractRemoteSharePublisher/TractRemoteSharePublisher.swift
  godtools/App/Services/TractRemoteShare/TractRemoteShareSubscriber/TractRemoteShareSubscriber.swift
  godtools/App/Services/UserAuthentication/Okta/OktaAuthenticationConfiguration.swift
  godtools/App/Services/Views/ViewsApi.swift
  godtools/App/Services/Views/ViewsService.swift
  godtools/App/Share/Data/AppConfig/AppBuild.swift
  godtools/App/Share/Data/AppConfig/AppConfig.swift
  godtools/App/Share/Data/TranslationsRepository/Api/MobileContentTranslationsApi.swift
Labels: Cru - Ready for Review, Refactor For Combine

#1305 GT-1762 tool details clean up
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Languages/LanguagesList/LanguagesListViewModel.swift
  godtools/App/Features/Languages/LanguagesList/Subviews/LanguagesListItemViewModel.swift
  godtools/App/Features/ToolDetails/ToolDetailsView.swift
  godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
  godtools/App/Services/Resources/ResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
  godtools/App/Share/Domain/UseCases/GetLanguageUseCase/LanguageDomainModel.swift
  godtools/App/Share/Domain/UseCases/GetToolLanguagesUseCase/GetToolLanguagesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolLanguagesUseCase/ToolLanguageModel.swift
  godtools/App/Share/Domain/UseCases/GetToolVersionsUseCase/GetToolVersionsUseCase.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1311 GT-1761 receive on main if not already on main
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Share/Extensions/Publisher+ReceiveOnMain.swift
Labels: Cru - Ready for Review

#1312 GT-1597 include spanish in quick links
  godtools/App/Share/Domain/UseCases/GetOnboardingQuickLinksEnabledUseCase/GetOnboardingQuickLinksEnabledUseCase.swift
  godtools/App/Share/LanguageCodes.swift
Labels: Cru - Ready for Review

#1309 GT-1765 Fix crash when cacheing RealmCategoryArticle with existing primaryKey
  godtools/App/Services/Articles/Categories/RealmCache/RealmCategoryArticle.swift
  godtools/App/Services/Articles/Categories/RealmCache/RealmCategoryArticlesCache.swift
  godtools/App/Services/Articles/Categories/Repository/ArticleManifestAemRepository.swift
Labels: Cru - Ready for Review, Release - Version 6.0.2

#1310 GT-1766 add store initial favorited tools use case
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppBackgroundState.swift
  godtools/App/DependencyContainer/AppDataLayerDependencies.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Share/Data/LaunchCountRepository/LaunchCountCache.swift
  godtools/App/Share/Data/LaunchCountRepository/LaunchCountRepository.swift
  godtools/App/Share/Domain/UseCases/BackgroundDownloadingUseCase/BackgroundDownloadingUseCase.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsUseCase/GetAllFavoritedToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/StoreInitialFavoritedToolsUseCase/StoreInitialFavoritedToolsUseCase.swift
Labels: Cru - Ready for Review, Release - Version 6.0.2

#1314 GT-1764 use new receiveOnMain in viewModel publishers
  godtools/App/Features/Languages/ChooseLanguage/ChooseLanguageViewModel.swift
  godtools/App/Features/Languages/LanguageSettings/LanguageSettingsViewModel.swift
  godtools/App/Features/SetupParallel/Views/ParallelLanguageListViewModel.swift
  godtools/App/Features/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardViewModel.swift
  godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/LessonCardViewModel.swift
Labels: Cru - Ready for Review, Release - Version 6.0.2

#1315 Merge develop into master for new QA release
  Podfile
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppBackgroundState.swift
  godtools/App/DependencyContainer/AppDataLayerDependencies.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Languages/ChooseLanguage/ChooseLanguageViewModel.swift
  godtools/App/Features/Languages/LanguageSettings/LanguageSettingsViewModel.swift
  godtools/App/Features/SetupParallel/Views/ParallelLanguageListViewModel.swift
  godtools/App/Features/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardViewModel.swift
  godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Services/Articles/Categories/RealmCache/RealmCategoryArticle.swift
  godtools/App/Services/Articles/Categories/RealmCache/RealmCategoryArticlesCache.swift
  godtools/App/Services/Articles/Categories/Repository/ArticleManifestAemRepository.swift
  godtools/App/Services/InitialDataDownloader/InitialDataDownloader.swift
  godtools/App/Services/RealmDatabase/Realm+SafeWrite.swift
  godtools/App/Services/RealmDatabase/RealmDatabase.swift
  godtools/App/Share/Data/FavoritedResourcesRepository/Cache/FavoritedResourcesCache.swift
  godtools/App/Share/Data/LanguagesRepository/Api/Models/LanguageModel.swift
  godtools/App/Share/Data/LaunchCountRepository/LaunchCountCache.swift
  godtools/App/Share/Data/LaunchCountRepository/LaunchCountRepository.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/Sync/RealmResourcesCacheSync.swift
  godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
  godtools/App/Share/Domain/UseCases/BackgroundDownloadingUseCase/BackgroundDownloadingUseCase.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsUseCase/GetAllFavoritedToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetOnboardingQuickLinksEnabledUseCase/GetOnboardingQuickLinksEnabledUseCase.swift
  godtools/App/Share/Domain/UseCases/StoreInitialFavoritedToolsUseCase/StoreInitialFavoritedToolsUseCase.swift
  godtools/App/Share/Extensions/Publisher+ReceiveOnMain.swift
  godtools/App/Share/LanguageCodes.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/LessonCardViewModel.swift
Labels: Release - Version 6.0.2

#1317 GT-1722 add run script for downloading resources, languages, and attachments to app bundle
  DownloadInitialResourcesScript
  GetResourcesScript
  Scripts/Scripts/DownloadInitialResources/DownloadInitialResourcesScript.swift
  Scripts/Scripts/DownloadInitialResources/GetResourcesAndLanguagesData.swift
  Scripts/Scripts/DownloadInitialResources/GetResourcesAttachments.swift
  godtools.xcodeproj/project.pbxproj
  godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
  godtools/App/DependencyContainer/AppDataLayerDependencies.swift
  godtools/App/Services/InitialDataDownloader/InitialDataDownloader.swift
  godtools/App/Services/Resources/ResourcesCache.swift
  godtools/App/Share/Data/AttachmentsRepository/Api/Models/AttachmentModel.swift
  godtools/App/Share/Data/AttachmentsRepository/Api/Models/AttachmentModelType.swift
  godtools/App/Share/Data/AttachmentsRepository/AttachmentFileDataModel.swift
  godtools/App/Share/Data/AttachmentsRepository/AttachmentsRepository.swift
  godtools/App/Share/Data/AttachmentsRepository/Bundle/AttachmentsBundleCache.swift
  godtools/App/Share/Data/AttachmentsRepository/Cache/Models/RealmAttachment.swift
  godtools/App/Share/Data/AttachmentsRepository/Cache/RealmAttachmentsCache.swift
  godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModel.swift
  godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModelDefaultVariantData.swift
  godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModelMetatoolData.swift
  godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModelType.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/Models/RealmResource.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
  godtools/App/Share/Data/ResourcesSHA256FileCache/SHA256FileModel.swift
  godtools/App/Share/Data/TranslationsRepository/Api/Models/TranslationModel.swift
  godtools/App/Share/Data/TranslationsRepository/Api/Models/TranslationModelType.swift
  godtools/App/Share/Data/TranslationsRepository/Cache/Models/RealmTranslation.swift
  godtools/App/Share/Data/TranslationsRepository/Cache/RealmTranslationsCache.swift
  godtools/Assets/InitialResources/attachment_about_banners/298732618f6a220d016b5493508c038a8c821780ea699627d03d4a6035d3f6bb.jpg
  godtools/Assets/InitialResources/attachment_about_banners/8a2312f958cdf6548a1637347bf89560f6ebf284549669638dfef944d8268a08.jpg
  godtools/Assets/InitialResources/attachment_about_banners/8a2312f958cdf6548a1637347bf89560f6ebf284549669638dfef944d8268a08.jpg alias
  godtools/Assets/InitialResources/attachment_about_banners/95ad213fe1106f7a12d0f0f7c1f82e53200021d7759bb543eb36cde626e37658.jpg
  godtools/Assets/InitialResources/attachment_about_banners/9a8cfa08121f0f0e78dbed54652c2c3f1d51c001a0b81dfdd092d378fd43633c.jpg
  godtools/Assets/InitialResources/attachment_about_banners/d84e2ee6bc7b949ac74213678a72487e511313579eeb6ace9f03364f31e41f19.jpg
  godtools/Assets/InitialResources/attachment_about_banners/db11fd9214b9a05b5d1e760c707e9db8d4b821dea36bca0c94263efa28e8ac4b.png
  godtools/Assets/InitialResources/attachment_about_banners/e961f409d06308e87deb9ed9166264c7c732d9dc24e70f886944636308810d6e.png
  godtools/Assets/InitialResources/attachment_banners/057e056ad4c27921d537c74f8e59396214330a1ed084efcb5d265d01cb7f0d4e.jpg
  godtools/Assets/InitialResources/attachment_banners/1958f6ba22b659adfc7eb43dcfac7cc5cfe192df45437355aa99a8752192ed92.jpg
  godtools/Assets/InitialResources/attachment_banners/2626c83091f11eb08c2bded5d4a237fa986fe3a318d1fb14933906021a7493a7.jpg
  godtools/Assets/InitialResources/attachment_banners/36ec96dc7e53cf2387e448a34740c599fe6fb3c51a597fc49667664ca2828e52.jpg
  godtools/Assets/InitialResources/attachment_banners/85ee4662cc5e6d7794928aee69a73bee6714e7c76d131040a8e0352e9c529588.jpg
  godtools/Assets/InitialResources/attachment_banners/86c8e65bddaa4b889e572aa89714ee846f27294abc62b69d291b52ea1cc05144.jpg
  godtools/Assets/InitialResources/attachment_banners/a6765002e46cea44dc6245bcb842ce01a0134c147c47cf108134a4c4d1a5c129.jpg
  godtools/Assets/InitialResources/attachment_banners/bae08d104b5ad1e9d7f97a25a88800adbce94cf36c508deaf3a2067f45919a36.png
  godtools/Assets/InitialResources/attachment_banners/e5dd66976d53a69bbd12867079750e14732c5112a254022c038738f7f12953a8.png
  godtools/Assets/InitialResources/attachment_banners/e999c849242ba4abf20560274f92dd6c77631992d10db0eca5515e80ffb431c6.jpg
  godtools/Assets/InitialResources/languages.json
  godtools/Assets/InitialResources/resources.json
Labels: Cru - Ready for Review, Release - Version 6.0.2

#1320 GT-1755 swift UI preview development assets
  godtools.xcodeproj/project.pbxproj
  godtools/App/Share/Domain/UseCases/GetBannerImageUseCase/GetBannerImageUseCase.swift
  godtools/App/Share/SwiftUI Views/ResourceCard Subviews/ResourceCardBannerImageView.swift
  godtools/Preview Content/Preview Assets.xcassets/Contents.json
  godtools/Preview Content/Preview Assets.xcassets/previewBannerImage.imageset/Contents.json
  godtools/Preview Content/Preview Assets.xcassets/previewBannerImage.imageset/bae08d104b5ad1e9d7f97a25a88800adbce94cf36c508deaf3a2067f45919a36 copy.png
Labels: Cru - Ready for Review

#1322 GT-1769 fix downloading tool alert
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/DownloadTool/DownloadTool/DownloadToolViewModel.swift
  godtools/App/Flows/DownloadToolTranslations/DownloadToolTranslationsFlow.swift
  godtools/App/Flows/FlowStep.swift
  godtools/App/Flows/NetworkErrorAlert/Flow+NetworkErrorAlert.swift
  godtools/App/Flows/ToolNavigation/ToolNavigationFlow.swift
  godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
  godtools/App/Share/Data/URLResponseError.swift
  godtools/App/Share/Data/URLResponseObject.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
  godtools/App/Share/Extensions/Error+NetworkError.swift
  godtools/App/Share/Views/AlertMessageView/Models/ResponseErrorAlertMessage.swift
Labels: Cru - Ready for Review, Release - Version 6.0.2

#1324 GT-1741 remove deprecated code
  godtools.xcodeproj/project.pbxproj
  godtools/App/Services/Attachments/AttachmentsDownloaderError.swift
  godtools/App/Services/Attachments/DownloadAttachmentsReceipt.swift
  godtools/App/Services/Attachments/DownloadedAttachmentResult.swift
  godtools/App/Services/Attachments/NoAttachmentData.swift
  godtools/App/Services/InitialDataDownloader/InitialDataDownloaderError.swift
  godtools/App/Services/Resources/DownloadResourceTranslationsReceipts.swift
  godtools/App/Services/Resources/RealmResourcesCache/ResourcesCacheResult.swift
  godtools/App/Services/Resources/ResourcesCache.swift
  godtools/App/Services/Resources/ResourcesDownloaderError.swift
  godtools/App/Services/Resources/ResourcesDownloaderResult.swift
  godtools/App/Services/TranslationsDownloader/DownloadedTranslationResult.swift
  godtools/App/Services/TranslationsDownloader/NoTranslationZipData.swift
  godtools/App/Services/TranslationsDownloader/TranslationDownloaderError.swift
  godtools/App/Services/TranslationsRepository/FileCache/Models/RealmTranslationZipFile.swift
  godtools/App/Services/TranslationsRepository/FileCache/Models/TranslationZipFileModel.swift
  godtools/App/Services/TranslationsRepository/FileCache/Models/TranslationZipFileModelType+ManifestSHA256FileLocation.swift
  godtools/App/Services/TranslationsRepository/FileCache/Models/TranslationZipFileModelType.swift
  godtools/App/Services/TranslationsRepository/FileCache/TranslationManifestData.swift
  godtools/App/Services/TranslationsRepository/FileCache/TranslationsFileCacheError.swift
  godtools/App/Share/Data/LanguagesRepository/Api/MobileContentLanguagesApi.swift
  godtools/App/Share/Data/LanguagesRepository/Cache/RealmLanguagesCache.swift
  godtools/App/Share/Data/ResourcesSHA256FileCache/SHA256FilesCache.swift
  godtools/App/Share/Data/TranslationsRepository/Api/MobileContentTranslationsApi.swift
  godtools/App/Share/Domain/ViewModels/Language/LanguageViewModel.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1329 Merge develop into master for new QA release
  godtools/vi.lproj/Localizable.strings
Labels: Release - Version 6.0.2

#1330 GT-1727 remove SharedSessionType protocol
  godtools.xcodeproj/project.pbxproj
  godtools/App/Services/Articles/Repository/Cache/ArticleAemCache.swift
  godtools/App/Services/Articles/Repository/Downloader/ArticleAemDownloader.swift
  godtools/App/Services/EmailSignUp/EmailSignUpApi.swift
  godtools/App/Services/EmailSignUp/EmailSignUpService.swift
  godtools/App/Services/FollowUps/FollowUpsApi.swift
  godtools/App/Services/FollowUps/FollowUpsService.swift
  godtools/App/Services/GlobalActivity/GlobalActivityAnalyticsApi.swift
  godtools/App/Services/GlobalActivity/GlobalActivityServices.swift
  godtools/App/Services/URLSession/SharedIgnoreCacheSession.swift
  godtools/App/Services/URLSession/SharedSessionType.swift
  godtools/App/Services/Views/ViewsApi.swift
  godtools/App/Services/Views/ViewsService.swift
  godtools/App/Services/WebArchiver/WebArchiveQueue.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1332 GT-Remove executables from repo and project for downloading initial resources
  .gitignore
  DownloadInitialResourcesScript
  GetResourcesScript
Labels: Cru - Ready for Review

#1327 GT 1736 Remove LanguageSettingsService in some places of the app
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/Features/Lessons/LessonEvaluation/LessonEvaluationViewModel.swift
  godtools/App/Features/SetupParallel/SetupParallelLanguageViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/ToolNavigation/ToolNavigationFlow.swift
  godtools/App/Services/LanguageDirection/LanguageDirection.swift
  godtools/App/Services/LanguageDirection/LanguageDirectionService.swift
  godtools/App/Services/Localization/LocalizationBundleLoader.swift
  godtools/App/Services/Localization/LocalizationServices.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Card/ToolPageCardViewModel.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/DetermineToolTranslationsToDownload/DetermineDeepLinkedToolTranslationsToDownload.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1328 GT-1774 add GetShortcutItemsUseCase
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDelegate.swift
  godtools/App/AppDiContainer.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Services/ShortcutItems/ShortcutItemsService.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/GetShortcutItemsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/ShortcutItemType.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/ToolShortcutItem.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1331 GT-1742 get spotlight tools use case
  godtools.xcodeproj/project.pbxproj
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardNavButtonView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardVerticalTextView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/ToolSpotlightView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/ViewModels/ToolSpotlightViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModel.swift
  godtools/App/Features/Tools/Views/Tool/ToolItemInitialDownloadProgress.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
  godtools/App/Share/Domain/UseCases/GetAllToolsUseCase/GetAllToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetSpotlightToolsUseCase/GetSpotlightToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolIsFavoritedUseCase/GetToolIsFavoritedUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolUseCase/GetToolUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolUseCase/ToolDomainModel.swift
  godtools/App/Share/Domain/ViewModels/ToolCardProvider.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/LessonCardViewModel.swift
  godtools/App/Share/SwiftUI Views/ToolCardsCarouselView/ToolCardsCarouselView.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1334 GT-1742 finish mapping resource model
  godtools.xcodeproj/project.pbxproj
  godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
  godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModel.swift
  godtools/App/Share/Domain/UseCases/GetLanguageAvailabilityStringUseCase/GetLanguageAvailablityStringUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolIsFavoritedUseCase/GetToolIsFavoritedUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolUseCase/GetToolUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolUseCase/ToolDomainModel.swift
  godtools/App/Share/Domain/UseCases/ToggleToolFavoritedUseCase/ToggleToolFavoritedUseCase.swift
  godtools/App/Share/Protocols/LanguageSupportable.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1337 GT remove analytics protocols
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/Services/Analytics/AnalyticsContainer.swift
  godtools/App/Services/Analytics/AnalyticsTracking/ExitLinkAnalytics.swift
  godtools/App/Services/Analytics/AnalyticsTracking/LessonFeedback/LessonFeedbackAnalytics.swift
  godtools/App/Services/Analytics/AnalyticsTracking/PageViewedAnalytics.swift
  godtools/App/Services/Analytics/AnalyticsTracking/ToolOpenedAnalytics.swift
  godtools/App/Services/Analytics/AnalyticsTracking/TrackActionAnalytics.swift
  godtools/App/Services/Analytics/AppsFlyer/AppsFlyerAnalytics.swift
  godtools/App/Services/Analytics/AppsFlyer/AppsFlyerAnalyticsType.swift
  godtools/App/Services/Analytics/Firebase/FirebaseAnalytics.swift
  godtools/App/Services/Analytics/Firebase/FirebaseAnalyticsType.swift
  godtools/App/Services/Analytics/Snowplow/SnowplowAnalytics.swift
  godtools/App/Services/Analytics/Snowplow/SnowplowAnalyticsType.swift
  godtools/App/Services/AppsFlyer/AppsFlyer.swift
  godtools/App/Services/AppsFlyer/AppsFlyerType.swift
  godtools/App/Services/Renderer/Analytics/MobileContentEventAnalyticsTracking.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1339 GT fix to resources sync when running in debug
  godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine
