Repository CruGlobal/godtools-swift, pull requests merged in 2022-06, with the labels that each got.

#1157 GT-1568 localize strings in tool settings
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/BaseToolSettingsChooseLanguageViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/ToolSettingsChooseLanguageView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/ToolSettingsChooseLanguageViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/BaseToolSettingsOptionsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsShareables/BaseToolSettingsShareablesViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsShareables/ToolSettingsShareablesView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsShareables/ToolSettingsShareablesViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsTopBar/BaseToolSettingsTopBarViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsTopBar/ToolSettingsTopBarView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsTopBar/ToolSettingsTopBarViewModel.swift
  godtools/App/Flows/DownloadToolTranslations/DownloadToolTranslationsFlow.swift
  godtools/Base.lproj/Localizable.strings
Labels: Cru - Ready for Review, iOS 13

#1165 GT-1584 Hide shareables section if there are no shareables
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/BaseToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
Labels: Cru - Ready for Review

#1172 GT-1614 Remove some base and mock view models for languages list
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/LanguagesList/Presentation/LanguagesList/BaseLanguagesListViewModel.swift
  godtools/App/Features/LanguagesList/Presentation/LanguagesList/LanguagesListView.swift
  godtools/App/Features/LanguagesList/Presentation/LanguagesList/LanguagesListViewModel.swift
  godtools/App/Features/LanguagesList/Presentation/LanguagesList/MockLanguagesListViewModel.swift
  godtools/App/Features/LanguagesList/Presentation/LanguagesList/Views/LanguagesListItemView.swift
  godtools/App/Features/LanguagesList/Presentation/LanguagesList/Views/MockLanguagesListItemViewModel.swift
Labels: Cru - Ready for Review

#1171 GT-1613 ToolSettings create and use single viewModel
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/BaseToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewPreview.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/BaseToolSettingsChooseLanguageViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/ToolSettingsChooseLanguageView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/ToolSettingsChooseLanguageViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/ToolSettingsLanguageDropDownView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/BaseToolSettingsOptionsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/Models/ToolSettingsOptionItemBackgroundType.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/Models/ToolSettingsOptionItemTitleColorStyle.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsItemView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/Views/ToolSettingsOptionsItemViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsSeparatorView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsShareables/BaseToolSettingsShareablesViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsShareables/ToolSettingsShareableItemView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsShareables/ToolSettingsShareableItemViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsShareables/ToolSettingsShareablesView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsShareables/ToolSettingsShareablesViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsShareables/Views/BaseToolSettingsShareableItemViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsShareables/Views/MockToolSettingsShareableItemViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsTopBar/BaseToolSettingsTopBarViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsTopBar/ToolSettingsTopBarViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsTopBarView.swift
  godtools/App/Features/ToolTraining/Presentation/ToolTraining/ToolTrainingView.swift
  godtools/App/Features/ToolTraining/Presentation/ToolTraining/ToolTrainingView.xib
  godtools/App/Features/ToolTraining/Presentation/ToolTraining/ToolTrainingViewModel.swift
  godtools/App/Features/ToolTraining/Presentation/ToolTraining/ToolTrainingViewModelType.swift
  godtools/App/Features/ToolTraining/Presentation/ToolTraining/Transitioning/ToolTrainingAnimatedTransitioning.swift
  godtools/App/Features/ToolTraining/Presentation/ToolTraining/Views/ToolTrainingTipView.swift
  godtools/App/Features/ToolTraining/Presentation/ToolTraining/Views/ToolTrainingTipView.xib
Labels: Cru - Ready for Review

#1173 GT-1567 tool settings change line spacing and parallel language spacing
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewPreview.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/ToolSettingsChooseLanguageView.swift
  godtools/Base.lproj/Localizable.strings
Labels: Cru - Ready for Review

#1160 GT-1265 all tools categories
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardBannerImageView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardCategoryView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardFavoritedView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardParallelLanguageView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardProgressView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardTitleView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/BaseToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/MockToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/ToolCategoriesView/ToolCategoriesView.swift
  godtools/App/Features/Tools/SwiftUI/ToolCategoriesView/ToolCategoriesViewModel.swift
  godtools/App/Features/Tools/SwiftUI/ToolCategoriesView/ToolCategoryButtonView/ToolCategoryButtonState.swift
  godtools/App/Features/Tools/SwiftUI/ToolCategoriesView/ToolCategoryButtonView/ToolCategoryButtonView.swift
  godtools/App/Features/Tools/SwiftUI/ToolCategoriesView/ToolCategoryButtonView/ViewModels/BaseToolCategoryButtonViewModel.swift
  godtools/App/Features/Tools/SwiftUI/ToolCategoriesView/ToolCategoryButtonView/ViewModels/ToolCategoryButtonViewModel.swift
  godtools/App/Features/Tools/SwiftUI/ToolSpotlightView/Subviews/SpotlightTitleView.swift
  godtools/App/Features/Tools/SwiftUI/ToolSpotlightView/Subviews/SpotlightToolCardsView.swift
  godtools/App/Features/Tools/SwiftUI/ToolSpotlightView/ToolSpotlightView.swift
  godtools/App/Features/Tools/SwiftUI/ToolSpotlightView/ViewModels/ToolSpotlightViewModel.swift
  godtools/App/Services/Localization/LocalizationBundleLoader.swift
  godtools/App/Services/Localization/LocalizationServices.swift
  godtools/App/Services/Resources/ResourcesApi/Models/ResourceModel.swift
  godtools/App/Services/Resources/ResourcesApi/Models/ResourceType.swift
  godtools/App/Services/Resources/ResourcesCache.swift
  godtools/App/Share/ColorPalette.swift
  godtools/App/Share/Extensions/Array+ResourceModel.swift
  godtools/App/Share/SwiftUI Modifiers/OptionalRoundedBorder.swift
  godtools/App/Share/SwiftUI Views/RoundedCardBackgroundView.swift
  godtools/App/Share/SwiftUI Views/SeparatorView.swift
  godtools/App/Share/SwiftUI Views/TwoRowHGrid.swift
  godtools/Assets.xcassets/Colors/gtLightestGrey.colorset/Contents.json
Labels: Cru - Ready for Review

#1169 GT-1612 recreate tool details in swift UI for meta
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/DownloadTool/Domain/GetToolTranslationsUseCase/GetToolTranslationsUseCase.swift
  godtools/App/Features/Onboarding/Views/OnboardingTutorialIntroView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsHostingView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/ToolDetailsAboutView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/ToolDetailsMediaType.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/ToolDetailsMediaView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/ToolDetailsPrimaryButtonsView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/ToolDetailsTitleHeaderView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/ToolDetailsToggleFavoriteButton.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/ToolDetailsVersionsView.swift
  godtools/App/Features/ToolDetails/ToolDetailViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentEmbeddedVideo/MobileContentEmbeddedVideoViewModel.swift
  godtools/App/Share/ImageCatalog.swift
  godtools/App/Share/Strings.swift
  godtools/App/Share/SwiftUI Preferences/ViewGeometry.swift
  godtools/App/Share/SwiftUI Preferences/ViewSizePreferenceKey.swift
  godtools/App/Share/SwiftUI Views/AnimatedSwiftUIView/AnimatedSwiftUIView.swift
  godtools/App/Share/SwiftUI Views/SegmentControl/Segment.swift
  godtools/App/Share/SwiftUI Views/SegmentControl/SegmentControl.swift
  godtools/App/Share/SwiftUI Views/TextWithLinks/TextViewLinksCoordinator.swift
  godtools/App/Share/SwiftUI Views/TextWithLinks/TextWithLinks.swift
  godtools/App/Share/SwiftUI Views/VideoView/VideoView.swift
  godtools/App/Share/SwiftUI Views/VideoView/VideoViewCoordinator.swift
  godtools/App/Share/Views/TutorialCell/TutorialCellViewModel.swift
  godtools/App/Share/Views/VideoPlayerView/VideoPlayerView.swift
  godtools/Assets.xcassets/Colors/gtBlue.colorset/Contents.json
  godtools/Assets.xcassets/Colors/progressBarBlue.colorset/Contents.json
  godtools/Base.lproj/Localizable.strings
Labels: Cru - Ready for Review

#1175 GT-1509 all tools fixes
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/Views/Tool/ToolCellViewModel.swift
  godtools/App/Share/Extensions/LanguageViewModel+String.swift
Labels: Ready to Merge

#1179 GT-1629 add back nav button to tool details and add to flow
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsHostingView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/FlowStep.swift
  godtools/App/Share/Extensions/UIViewController+NavBackItem.swift
Labels: Ready to Merge

#1177 GT-1551 add review shareable image to tool settings flow
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/ToolSettings/Presentation/ReviewShareShareable/ReviewShareShareableHostingView.swift
  godtools/App/Features/ToolSettings/Presentation/ReviewShareShareable/ReviewShareShareableView.swift
  godtools/App/Features/ToolSettings/Presentation/ReviewShareShareable/ReviewShareShareableViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ShareShareable/ShareShareableViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
  godtools/App/Flows/FlowStep.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
  godtools/App/Share/ImageCatalog.swift
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_share_image_button_icon.imageset/Contents.json
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_share_image_button_icon.imageset/tool_settings_share_image_button_icon.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_share_image_button_icon.imageset/tool_settings_share_image_button_icon@2x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_share_image_button_icon.imageset/tool_settings_share_image_button_icon@3x.png
  godtools/Base.lproj/Localizable.strings
Labels: Ready to Merge

#1180 GT-1627 Use language translatedLanguageName in languages list
  godtools/App/AppDiContainer.swift
  godtools/App/Features/LanguagesList/Domain/GetToolLanguagesUseCase/GetToolLanguagesUseCase.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
Labels: Ready to Merge

#1182 GT-1619 ToolSettings filter choose primary and parallel language lists
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
Labels: Cru - Ready for Review

#1183 GT-1624 create share domain directory
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/Features/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
  godtools/App/Features/Languages/ChooseLanguageViewModel.swift
  godtools/App/Features/Languages/LanguageSettingsViewModel.swift
  godtools/App/Features/Languages/Views/ChooseLanguageCellViewModel.swift
  godtools/App/Features/SetupParallel/SetupParallelLanguageViewModel.swift
  godtools/App/Features/SetupParallel/Views/ParallelLanguageListViewModel.swift
  godtools/App/Features/Tool/ToolViewModel.swift
  godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarViewModel.swift
  godtools/App/Features/Tool/Views/ToolNavBar/ViewModels/ToolLanguageSegmentViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewPreview.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
  godtools/App/Flows/LanguageSettings/LanguageSettingsFlow.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
  godtools/App/Flows/Tract/TractFlow.swift
  godtools/App/Share/Domain/Extensions/Array+ResourceModel.swift
  godtools/App/Share/Domain/UseCases/GetTranslatedLanguageUseCase/GetTranslatedLanguageUseCase.swift
  godtools/App/Share/Domain/UseCases/GetTranslatedLanguageUseCase/TranslatedLanguage.swift
  godtools/App/Share/Domain/UseCases/GetTutorialIsAvailableUseCase/GetTutorialIsAvailableUseCase.swift
  godtools/App/Share/Domain/UseCases/GetTutorialIsAvailableUseCase/TutorialLanguageAvailability.swift
  godtools/App/Share/Domain/UseCases/GetTutorialIsAvailableUseCase/TutorialSupportedLanguages.swift
  godtools/App/Share/Domain/UseCases/GetTutorialIsAvailableUseCase/TutorialSupportedLanguagesType.swift
  godtools/App/Share/Domain/ViewModels/DownloadToolError/DownloadToolErrorViewModel.swift
  godtools/App/Share/Domain/ViewModels/Language/LanguageViewModel.swift
Labels: Cru - Ready for Review

#1181 GT-1626 Update ToolSettings when tool renderer changes
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
  godtools/App/Features/Lessons/Lesson/LessonViewModel.swift
  godtools/App/Features/Tool/ToolViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewPreview.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/ToolSettingsChooseLanguageView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsView.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlowToolData.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
Labels: Cru - Ready for Review

#1186 GT-1636 fix content sections to render content stack instead of single text element
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordion/MobileContentAccordionView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.xib
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentStack/MobileContentStackView.swift
Labels: Cru - Ready for Review

#1188 GT-1640 Hide navigation bar when viewing a lesson
  godtools/App/Features/Lessons/Lesson/LessonView.swift
Labels: Cru - Ready for Review

#1190 GT-1418 about versions selection
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Models/ToolDetailsSegmentType.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
Labels: Cru - Ready for Review

#1193 GT-1631 no favorite tools
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Tools/FavoritedToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/FavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/Subviews/FavoriteToolsHeaderView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/Subviews/NoFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/FavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuView.swift
  godtools/Base.lproj/Localizable.strings
Labels: Ready to Merge

#1195 GT-1643 favorite page tutorial
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Tools/FavoritedToolsView.swift
  godtools/App/Features/Tools/FavoritedToolsViewModel.swift
  godtools/App/Features/Tools/FavoritedToolsViewModelType.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/FavoritingToolBannerView/FavoritingToolBannerView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/FavoritingToolBannerView/ViewModel/BaseFavoritingToolBannerViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/FavoritingToolBannerView/ViewModel/FavoritingToolBannerViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/OpenTutorialBannerView/OpenTutorialBannerView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/OpenTutorialBannerView/OpenTutorialBannerViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModel.swift
  godtools/App/Features/Tools/ToolsTableView.swift
  godtools/App/Features/Tools/ToolsTableView.xib
  godtools/App/Features/Tools/ToolsViewModelType.swift
  godtools/App/Features/Tools/Views/FavoritingToolMessageView/FavoritingToolMessageView.swift
  godtools/App/Features/Tools/Views/FavoritingToolMessageView/FavoritingToolMessageView.xib
  godtools/App/Features/Tools/Views/FavoritingToolMessageView/FavoritingToolMessageViewModel.swift
  godtools/App/Features/Tools/Views/FavoritingToolMessageView/FavoritingToolMessageViewModelType.swift
  godtools/App/Features/Tools/Views/OpenTutorialView/OpenTutorialView.swift
  godtools/App/Features/Tools/Views/OpenTutorialView/OpenTutorialView.xib
  godtools/App/Features/Tools/Views/OpenTutorialView/OpenTutorialViewModel.swift
  godtools/App/Features/Tools/Views/OpenTutorialView/OpenTutorialViewModelType.swift
  godtools/App/Features/Tools/Views/Tool/ToolCell.swift
  godtools/App/Features/Tools/Views/Tool/ToolCell.xib
  godtools/App/Features/Tools/Views/Tool/ToolCellViewModel.swift
  godtools/App/Features/Tools/Views/Tool/ToolCellViewModelType.swift
  godtools/App/Share/ImageCatalog.swift
  godtools/App/Share/SwiftUI Modifiers/BannerTextStyle.swift
  godtools/App/Share/SwiftUI Views/BackwardCompatibleList.swift
  godtools/App/Share/SwiftUI Views/BannerView/BannerView.swift
Labels: Cru - Ready for Review

#1199 GT-1632 featured lessons
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/LessonCardView/LessonCardView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/LessonCardView/ViewModels/BaseLessonCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/LessonCardView/ViewModels/LessonCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/LessonCardView/ViewModels/MockLessonCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/LessonCardsView/LessonCardsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/LessonCardsView/LessonCardsViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/FlowStep.swift
  godtools/App/Services/Resources/ResourcesApi/Models/ResourceModel.swift
  godtools/App/Services/Resources/ResourcesApi/Models/ResourceType.swift
  godtools/App/Services/Resources/ResourcesCache.swift
  godtools/App/Share/Domain/Extensions/Array+ResourceModel.swift
  godtools/App/Share/Domain/ViewModels/LessonCardProvider.swift
  godtools/App/Share/SwiftUI Views/ResourceCard Subviews/ResourceCardBannerImageView.swift
  godtools/App/Share/SwiftUI Views/ResourceCard Subviews/ResourceCardProgressView.swift
  godtools/Base.lproj/Localizable.strings
Labels: Cru - Ready for Review

#1207 GT-1657 Change quick links to support english only
  godtools/App/Share/Domain/UseCases/GetOnboardingQuickLinksEnabledUseCase/GetOnboardingQuickLinksEnabledUseCase.swift
Labels: Cru - Ready for Review

#1205 GT-1418 Update tool version card selection state
  godtools/App/Features/ToolDetails/Domain/GetToolVersionsUseCase/GetToolVersionsUseCase.swift
  godtools/App/Features/ToolDetails/Domain/GetToolVersionsUseCase/ToolVersionDomainModel.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/ToolDetailsVersionsView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/VersionsCard/ToolDetailsVersionsCardView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/VersionsCard/ToolDetailsVersionsCardViewModel.swift
  godtools/App/Share/SwiftUI Views/CircleSelector/CircleSelectorView.swift
Labels: Cru - Ready for Review

#1204 GT-1612 move background and frame into button itself
  Podfile.lock
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/ToolDetailsToggleFavoriteButton.swift
Labels: Cru - Ready for Review
