Repository CruGlobal/godtools-swift, pull requests merged in 2022-05, with the labels that each got.

#1099 GT-1509 All Tools in swift UI
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
  godtools/App/Features/SetupParallel/SetupParallelLanguageView.swift
  godtools/App/Features/ShareTool/ShareToolScreenTutorial/ShareToolScreenTutorialView.swift
  godtools/App/Features/Tools/AllToolsView.swift
  godtools/App/Features/Tools/AllToolsView.xib
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsListWithScrollToTop.swift
  godtools/App/Features/Tools/SwiftUI/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/SwiftUI/ToolCardView/ToolCardViewModel.swift
  godtools/App/Features/Tools/ToolsMenuView.swift
  godtools/App/Features/Tools/ToolsMenuViewModel.swift
  godtools/App/Features/Tools/ToolsMenuViewModelType.swift
  godtools/App/Features/Tools/Views/Tool/ToolCell.xib
  godtools/App/Flows/Menu/MenuFlow.swift
  godtools/App/Flows/MockFlowDelegate.swift
  godtools/App/Services/Resources/ResourcesApi/Models/ResourceModel.swift
  godtools/App/Share/ColorPalette.swift
  godtools/App/Share/Extensions/LayoutDirection+LanguageDirection.swift
  godtools/App/Share/Extensions/View+CustomModifiers.swift
  godtools/App/Share/SwiftUI Views/ActivityIndicator.swift
  godtools/App/Share/SwiftUI Views/OptionalImage.swift
  godtools/App/Share/SwiftUI Views/RoundedCorner.swift
  godtools/App/SwiftUIPreviewDiContainer.swift
  godtools/Assets.xcassets/Colors/Contents.json
  godtools/Assets.xcassets/Colors/gtBlue.colorset/Contents.json
  godtools/Assets.xcassets/Colors/gtGrey.colorset/Contents.json
  godtools/Assets.xcassets/Features/Tools/favorited_circle.imageset/Contents.json
  godtools/Assets.xcassets/Features/Tools/favorited_circle.imageset/Group 739unfavoritedCircle-2.pdf
  godtools/Assets.xcassets/Features/Tools/unfavorited_circle.imageset/Contents.json
  godtools/Assets.xcassets/Features/Tools/unfavorited_circle.imageset/Group 739unfavoritedCircle.pdf
  godtools/Assets/InitialResources/attachment_about_banners/8a2312f958cdf6548a1637347bf89560f6ebf284549669638dfef944d8268a08.jpg alias
Labels: iOS 13

#1105 GT-1505 upgrade google tag manager
  .github/workflows/build.yml
  .github/workflows/download_onesky_translations.yml
  Podfile
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
  godtools/App/Features/Tools/Views/ToolsMenuToolbar/ToolsMenuToolbarView.swift
  godtools/App/Flows/ArticleDeepLink/ArticleDeepLinkFlow.swift
  godtools/App/Flows/Lesson/LessonFlow.swift
  godtools/App/Services/Analytics/Firebase/FirebaseAnalytics.swift
  godtools/App/Services/AppsFlyer/AppsFlyer.swift
  godtools/App/Services/AppsFlyer/AppsFlyerType.swift
  godtools/App/Services/Attachments/AttachmentsFileCache.swift
  godtools/App/Services/InitialDataDownloader/InitialDeviceResourcesLoader.swift
  godtools/App/Services/Renderer/Parser/RenderableModels/Concrete/MultiplatformContent.swift
  godtools/App/Services/Renderer/Parser/RenderableModels/Extensions/ContentPage+MobileContentRenderableModel.swift
  godtools/App/Services/Renderer/Parser/RenderableModels/Extensions/LessonPage+MobileContentRenderableModel.swift
  godtools/App/Services/Renderer/Views/ChooseYourOwnAdventure/ViewFactory/ChooseYourOwnAdventurePageViewFactory.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlowRow/MobileContentFlowRowItem.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentHeader/MobileContentHeaderViewModel.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentHeader/MobileContentHeaderViewModelType.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentLink/MobileContentLinkView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentMultiSelectOption/MobileContentMultiSelectOptionViewModel.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Heading/MobileContentHeadingView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/MobileContentViewModelType.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Page/MobileContentPageViewModel.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Page/MobileContentPageViewModelType.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Spacer/MobileContentSpacerViewModel.swift
  godtools/App/Services/Translations/TranslationsFileCache/TranslationsFileCache.swift
  godtools/App/Services/WebSocket/ActionCableChannelPublisher.swift
  godtools/App/Share/Extensions/UIButton+SetInsets.swift
  godtools/App/Share/Extensions/UIImage+CreateImageWithColor.swift
  godtools/App/Share/Extensions/UIImage+ScalePresevingAspectRatio.swift
  godtools/App/Share/Views/AnimatedView/AnimatedViewModel.swift
  godtools/App/Share/Views/AnimatedView/AnimatedViewModelType.swift
  godtools/godtools-Bridging-Header.h
Labels: Cru - Ready for Review

#1114 GT-1542 update font library and image catalog for swift UI
  godtools.xcodeproj/project.pbxproj
  godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
  godtools/App/Features/Lessons/LessonEvaluation/Views/PrimaryEvaluationOption/PrimaryEvaluationOptionButton.swift
  godtools/App/Features/Tools/SwiftUI/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/SwiftUI/ToolCardView/ViewModels/BaseToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/ToolCardView/ViewModels/MockToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Services/FontService/FontService.swift
  godtools/App/Share/ColorPalette.swift
  godtools/App/Share/FontLibrary.swift
  godtools/App/Share/ImageCatalog.swift
  godtools/App/Share/Views/GTSegmentControl/GTSegmentedControl.swift
  godtools/App/Share/Views/OnboardPrimaryButton/OnboardPrimaryButton.swift
  godtools/Assets.xcassets/Colors/gtLightGrey.colorset/Contents.json
Labels: Cru - Ready for Review, iOS 13

#1110 GT-1532 All Tools Favorite Messaging
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/FavoritingToolBannerView/FavoritingToolBannerView.swift
  godtools/App/Features/Tools/SwiftUI/FavoritingToolBannerView/ViewModel/BaseFavoritingToolBannerViewModel.swift
  godtools/App/Features/Tools/SwiftUI/FavoritingToolBannerView/ViewModel/FavoritingToolBannerViewModel.swift
  godtools/App/Features/Tools/SwiftUI/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/Views/FavoritingToolMessageView/FavoritingToolMessageView.swift
  godtools/App/Features/Tools/Views/OpenTutorialView/OpenTutorialView.swift
  godtools/App/Share/ColorPalette.swift
  godtools/Assets.xcassets/Colors/banner.colorset/Contents.json
Labels: Cru - Ready for Review, iOS 13

#1113 GT-1058 Add build script phase to download languages and resources json files
  godtools.xcodeproj/project.pbxproj
  godtools/Assets/InitialResources/languages.json
  godtools/Assets/InitialResources/resources.json
Labels: Cru - Ready for Review

#1121 GT-1493 bump to 13.1
  Podfile
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Cru - Ready for Review, iOS 13

#1119 GT-1489 Link tract to lessons list
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/Tract/TractFlow.swift
  godtools/App/Flows/Tract/TractFlowCompletedState.swift
Labels: Cru - Ready for Review

#1111 GT-1541 all tools remove scroll to top
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsListWithScrollToTop.swift
  godtools/App/Features/Tools/ToolsMenuView.swift
Labels: Cru - Ready for Review, iOS 13

#1118 Gt 1514 fix Vietnamese prayer pathway registration bug
  godtools.xcodeproj/project.pbxproj
  godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
  godtools/App/Services/Renderer/Analytics/MobileContentEventAnalyticsTracking.swift
  godtools/App/Services/Renderer/Views/MobileContent/Models/ProcessedEventResult/ProcessedEventResult.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentTabs/MobileContentTabsView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/MobileContentView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Page/MobileContentPageView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModelType.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Cards/ToolPageCardsView.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Form/ToolPageFormView.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Modal/ToolPageModalView.swift
Labels: Cru - Ready for Review

#1125 GT-1548 fix hidden cards
  godtools/App/Services/Renderer/Views/Tool/ViewFactory/ToolPageViewFactory.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Card/ToolPageCardView.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Card/ToolPageCardViewModel.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Card/ToolPageCardViewModelType.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Cards/ToolPageCardsView.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Cards/ToolPageCardsViewModel.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Cards/ToolPageCardsViewModelType.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Page/ToolPageView.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Page/ToolPageViewModel.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Page/ToolPageViewModelType.swift
  godtools/Assets/InitialResources/languages.json
  godtools/Assets/InitialResources/resources.json
Labels: Cru - Ready for Review

#1126 GT-1300 support animations in about banner
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/ToolDetails/Models/ToolDetailBannerType.swift
  godtools/App/Features/ToolDetails/ToolDetailView.swift
  godtools/App/Features/ToolDetails/ToolDetailView.xib
  godtools/App/Features/ToolDetails/ToolDetailViewModel.swift
  godtools/App/Features/ToolDetails/ToolDetailViewModelType.swift
  godtools/App/Services/Attachments/AttachmentsFileCache.swift
  godtools/App/Services/RealmDatabase/RealmDatabase.swift
  godtools/App/Services/Resources/RealmResourcesCache/Models/RealmResource.swift
  godtools/App/Services/Resources/ResourcesApi/Models/ResourceModel.swift
  godtools/App/Services/Resources/ResourcesApi/Models/ResourceModelType.swift
  godtools/App/Services/SHA256FileCache/SHA256FileLocation.swift
Labels: Cru - Ready for Review

#1131 GT-1555 add files for tool settings presentation and flow
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Tool/ToolView.swift
  godtools/App/Features/Tool/ToolViewModel.swift
  godtools/App/Features/Tool/ToolViewModelType.swift
  godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarView.swift
  godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarViewModel.swift
  godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarViewModelType.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsConfigureParallelLanguage/ToolSettingsConfigureParallelLanguageView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsConfigureParallelLanguage/ToolSettingsConfigureParallelLanguageViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsConfigureParallelLanguage/Views/ToolSettingsLanguageDropDownView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/Views/ToolSettingsOptionsItemView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/Views/ToolSettingsOptionsItemViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsRelatedContent/ToolSettingsRelatedContentView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsRelatedContent/ToolSettingsRelatedContentViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsRelatedContent/Views/ToolSettingsRelatedContentItemView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsSeparator/ToolSettingsSeparatorView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsTopBar/ToolSettingsTopBarView.swift
  godtools/App/Flows/FlowStep.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
  godtools/App/Flows/Tract/TractFlow.swift
  godtools/App/Share/ImageCatalog.swift
  godtools/App/Share/SwiftUI Views/LazyHList/LazyHList.swift
  godtools/App/Share/SwiftUI Views/LazyHList/LazyHListCoordinator.swift
  godtools/Assets.xcassets/NavigationItems/Contents.json
  godtools/Assets.xcassets/NavigationItems/nav_tool_settings.imageset/Contents.json
  godtools/Assets.xcassets/NavigationItems/nav_tool_settings.imageset/nav_tool_settings.png
  godtools/Assets.xcassets/NavigationItems/nav_tool_settings.imageset/nav_tool_settings@2x.png
  godtools/Assets.xcassets/NavigationItems/nav_tool_settings.imageset/nav_tool_settings@3x.png
Labels: Cru - Ready for Review, iOS 13

#1107 Upgrade shared parser
  Podfile
  Podfile.lock
  godtools/App/Services/Renderer/Parser/MobileContentParser.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentButton/MobileContentButtonViewModel.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentLink/MobileContentLinkViewModel.swift
  godtools/Assets/InitialResources/languages.json
  godtools/Assets/InitialResources/resources.json
Labels: 🛑 don't merge!

#1133 GT-1558 add tool settings and navigation
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Lessons/LessonEvaluation/LessonEvaluationView.swift
  godtools/App/Features/SetupParallel/SetupParallelLanguageView.swift
  godtools/App/Features/SetupParallel/Views/ParallelLanguageListView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/BaseToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsHostingView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsConfigureParallelLanguage/ToolSettingsConfigureParallelLanguageView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsConfigureParallelLanguage/Views/ToolSettingsLanguageDropDownView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/Views/Models/ToolSettingsOptionItemBackgroundType.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/Views/Models/ToolSettingsOptionItemTitleColorStyle.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/Views/ToolSettingsOptionsItemView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsTopBar/BaseToolSettingsTopBarViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsTopBar/ToolSettingsTopBarView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsTopBar/ToolSettingsTopBarViewModel.swift
  godtools/App/Flows/FlowStep.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlowCompletedState.swift
  godtools/App/Flows/Tract/TractFlow.swift
  godtools/App/Share/Extensions/UIView+Constraints.swift
  godtools/App/Share/ImageCatalog.swift
  godtools/App/Share/SwiftUI Views/RoundedCorner.swift
  godtools/App/Share/Views/TransparentModal/TransparentModalCustomView.swift
  godtools/App/Share/Views/TransparentModal/TransparentModalCustomViewLayoutType.swift
  godtools/App/Share/Views/TransparentModal/TransparentModalView.swift
  godtools/Assets.xcassets/Features/ToolSettings/Contents.json
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_language_dropdown_arrow.imageset/Contents.json
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_language_dropdown_arrow.imageset/tool_settings_language_dropdown_arrow.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_language_dropdown_arrow.imageset/tool_settings_language_dropdown_arrow@2x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_language_dropdown_arrow.imageset/tool_settings_language_dropdown_arrow@3x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_screen_share.imageset/Contents.json
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_screen_share.imageset/tool_settings_option_screen_share.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_screen_share.imageset/tool_settings_option_screen_share@2x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_screen_share.imageset/tool_settings_option_screen_share@3x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_share_link.imageset/Contents.json
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_share_link.imageset/tool_settings_option_share_link.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_share_link.imageset/tool_settings_option_share_link@2x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_share_link.imageset/tool_settings_option_share_link@3x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_training_tip_background.imageset/Contents.json
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_training_tip_background.imageset/tool_settings_option_training_tips_background.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_training_tip_background.imageset/tool_settings_option_training_tips_background@2x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_training_tip_background.imageset/tool_settings_option_training_tips_background@3x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_training_tips.imageset/Contents.json
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_training_tips.imageset/tool_settings_option_training_tips.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_training_tips.imageset/tool_settings_option_training_tips@2x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_training_tips.imageset/tool_settings_option_training_tips@3x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_swap_language.imageset/Contents.json
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_swap_language.imageset/tool_settings_swap_language.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_swap_language.imageset/tool_settings_swap_language@2x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_swap_language.imageset/tool_settings_swap_language@3x.png
Labels: Cru - Ready for Review, iOS 13

#1136 Add feature to GitHub Actions
  .github/workflows/build.yml
Labels: Cru - Ready for Review

#1135 GT-1558 tool settings with toggle training tips
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
  godtools/App/Features/Lessons/Lesson/LessonViewModel.swift
  godtools/App/Features/Tool/ToolView.swift
  godtools/App/Features/Tool/ToolViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/BaseToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/BaseToolSettingsOptionsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/Views/Models/ToolSettingsOptionItemBackgroundType.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/Views/ToolSettingsOptionsItemView.swift
  godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
  godtools/App/Flows/FlowStep.swift
  godtools/App/Flows/Lesson/LessonFlow.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlowCompletedState.swift
  godtools/App/Flows/Tract/TractFlow.swift
  godtools/App/Services/Renderer/Renderer/MobileContentPageRenderer.swift
  godtools/App/Services/Renderer/Renderer/MobileContentRenderedPageContext.swift
  godtools/App/Services/Renderer/Renderer/MobileContentRendererPageViewFactories.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
  godtools/App/Services/Renderer/Views/Tool/ViewFactory/ToolPageViewFactory.swift
  godtools/App/Services/Renderer/Views/Training/ViewFactory/TrainingViewFactory.swift
  godtools/App/Share/ImageCatalog.swift
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_hide_tips.imageset/Contents.json
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_hide_tips.imageset/tool_settings_option_hide_tips.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_hide_tips.imageset/tool_settings_option_hide_tips@2x.png
  godtools/Assets.xcassets/Features/ToolSettings/tool_settings_option_hide_tips.imageset/tool_settings_option_hide_tips@3x.png
Labels: Cru - Ready for Review, iOS 13

#1142 GT-1573 Fix home screen quick launch
  godtools/App/Services/DeepLinkingService/GodToolsManifest/GodToolsDeepLinkingManifest.swift
  godtools/App/Services/ShortcutItems/ToolShortcutItem.swift
Labels: Cru - Ready for Review

#1143 GT Increase version to 5.7.11
  godtools.xcodeproj/project.pbxproj
Labels: Cru - Ready for Review

#1140 GT-1574 fix stacked cards in tool renderer
  godtools/App/Services/Renderer/Views/Tool/Views/Cards/ToolPageCardsView.swift
Labels: Cru - Ready for Review

#1141 GT-1572 tool settings sharelink screenshare and present languages list
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/Features/LanguagesList/Domain/GetToolLanguagesUseCase/GetToolLanguagesUseCase.swift
  godtools/App/Features/LanguagesList/Domain/GetToolLanguagesUseCase/ToolLanguageModel.swift
  godtools/App/Features/LanguagesList/Presentation/LanguagesList/LanguagesListView.swift
  godtools/App/Features/LanguagesList/Presentation/LanguagesList/LanguagesListViewModel.swift
  godtools/App/Features/LanguagesList/Presentation/LanguagesList/Views/LanguagesListItemView.swift
  godtools/App/Features/LanguagesList/Presentation/LanguagesList/Views/LanguagesListItemViewModel.swift
  godtools/App/Features/Tool/ToolView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/BaseToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/BaseToolSettingsChooseLanguageViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/ToolSettingsChooseLanguageView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/ToolSettingsChooseLanguageViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/Views/ToolSettingsLanguageDropDownView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsConfigureParallelLanguage/ToolSettingsConfigureParallelLanguageViewModel.swift
  godtools/App/Flows/FlowStep.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlowCompletedState.swift
  godtools/App/Flows/ToolSettings/ToolSettingsLanguageListType.swift
  godtools/App/Flows/ToolSettings/ToolSettingsToolType.swift
  godtools/App/Flows/Tract/TractFlow.swift
  godtools/App/Services/LanguageTranslationsDownloader/LanguageTranslationsDownloader.swift
  godtools/App/Services/Languages/LanguagesApiType.swift
  godtools/App/Services/LanguagesRepository/LanguagesRepository.swift
  godtools/App/Services/LanguagesRepository/MobileContentApi/LanguageModel+Direction.swift
  godtools/App/Services/LanguagesRepository/MobileContentApi/LanguageModel.swift
  godtools/App/Services/LanguagesRepository/MobileContentApi/LanguageModelType.swift
  godtools/App/Services/LanguagesRepository/MobileContentApi/LanguagesDataModel.swift
  godtools/App/Services/LanguagesRepository/MobileContentApi/MobileContentLanguagesApi.swift
  godtools/App/Services/LanguagesRepository/RealmCache/RealmLanguage.swift
  godtools/App/Services/LanguagesRepository/RealmCache/RealmLanguagesCache.swift
  godtools/App/Services/Resources/ResourcesDownloader.swift
  godtools/App/Share/SwiftUI Views/CloseButton.swift
Labels: Cru - Ready for Review, iOS 13

#1147 GT remove translations api protocol and restructuring translations api and file cache
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/Services/Translations/TranslationsApi/TranslationsApiType.swift
  godtools/App/Services/TranslationsDownloader/DownloadTranslationsReceipt.swift
  godtools/App/Services/TranslationsDownloader/DownloadedTranslationResult.swift
  godtools/App/Services/TranslationsDownloader/NoTranslationZipData.swift
  godtools/App/Services/TranslationsDownloader/TranslationDownloader.swift
  godtools/App/Services/TranslationsDownloader/TranslationDownloaderError.swift
  godtools/App/Services/TranslationsRepository/FileCache/Models/RealmTranslationZipFile.swift
  godtools/App/Services/TranslationsRepository/FileCache/Models/TranslationZipFileModel.swift
  godtools/App/Services/TranslationsRepository/FileCache/Models/TranslationZipFileModelType+ManifestSHA256FileLocation.swift
  godtools/App/Services/TranslationsRepository/FileCache/Models/TranslationZipFileModelType.swift
  godtools/App/Services/TranslationsRepository/FileCache/TranslationManifestData.swift
  godtools/App/Services/TranslationsRepository/FileCache/TranslationsFileCache.swift
  godtools/App/Services/TranslationsRepository/FileCache/TranslationsFileCacheError.swift
  godtools/App/Services/TranslationsRepository/MobileContentApi/MobileContentTranslationsApi.swift
  godtools/App/Services/TranslationsRepository/TranslationsRepository.swift
Labels: Cru - Ready for Review

#1149 GT Change computed properties in AppDiContainer to methods to be consistent
  godtools/App/AppDelegate.swift
  godtools/App/AppDiContainer.swift
  godtools/App/Flows/Flow+NavigateToUrl.swift
  godtools/App/Flows/LearnToShareTool/LearnToShareToolFlow.swift
  godtools/App/Flows/Onboarding/OnboardingFlow.swift
  godtools/App/Flows/ShareToolMenu/ShareToolMenuFlow.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
  godtools/App/Flows/Tract/TractFlow.swift
Labels: Cru - Ready for Review

#1155 GT-1549 Prep for choose language in tool settings
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/Features/Tool/ToolViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsView.swift
  godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsTopBar/ToolSettingsTopBarView.swift
  godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
  godtools/App/Flows/DownloadToolTranslations/DownloadToolTranslationsFlow.swift
  godtools/App/Flows/DownloadToolTranslations/DownloadToolTranslationsFlowCompletedState.swift
  godtools/App/Flows/Lesson/LessonFlow.swift
  godtools/App/Services/Renderer/Renderer/MobileContentRendererPageViewFactories.swift
  godtools/App/Services/Renderer/Views/MobileContent/ViewFactory/MobileContentPageViewFactoryType.swift
  godtools/App/Services/Renderer/Views/Training/ViewFactory/TrainingViewFactory.swift
Labels: Cru - Ready for Review, iOS 13

#1156 GT-1565 remove share tool menu flow in place of tool settings flow
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/ShareTool/ShareToolMenu/ShareToolMenuView.swift
  godtools/App/Features/ShareTool/ShareToolMenu/ShareToolMenuViewModel.swift
  godtools/App/Features/ShareTool/ShareToolMenu/ShareToolMenuViewModelType.swift
  godtools/App/Features/ToolSettings/Data/ShareToolScreenTutorialItemProvider/ShareToolScreenTutorialItemProvider.swift
  godtools/App/Features/ToolSettings/Data/ShareToolScreenTutorialNumberOfViewsCache/ShareToolScreenTutorialNumberOfViewsCache.swift
  godtools/App/Features/ToolSettings/Presentation/LoadToolRemoteSession/LoadToolRemoteSessionViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ShareTool/ShareToolView.swift
  godtools/App/Features/ToolSettings/Presentation/ShareTool/ShareToolViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ShareTool/ShareToolViewModelType.swift
  godtools/App/Features/ToolSettings/Presentation/ShareToolRemoteSessionURL/ShareToolRemoteSessionURLView.swift
  godtools/App/Features/ToolSettings/Presentation/ShareToolRemoteSessionURL/ShareToolRemoteSessionURLViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ShareToolRemoteSessionURL/ShareToolRemoteSessionURLViewModelType.swift
  godtools/App/Features/ToolSettings/Presentation/ShareToolScreenTutorial/ShareToolScreenCustomTutorialViewBuilder.swift
  godtools/App/Features/ToolSettings/Presentation/ShareToolScreenTutorial/ShareToolScreenTutorialView.swift
  godtools/App/Features/ToolSettings/Presentation/ShareToolScreenTutorial/ShareToolScreenTutorialView.xib
  godtools/App/Features/ToolSettings/Presentation/ShareToolScreenTutorial/ShareToolScreenTutorialViewModel.swift
  godtools/App/Features/ToolSettings/Presentation/ShareToolScreenTutorial/ShareToolScreenTutorialViewModelType.swift
  godtools/App/Flows/FlowStep.swift
  godtools/App/Flows/ShareToolMenu/ShareToolMenuFlow.swift
  godtools/App/Flows/Tract/TractFlow.swift
Labels: Cru - Ready for Review, iOS 13
