Repository CruGlobal/godtools-swift, pull requests merged in 2022-09, with the labels that each got.

#1338 GT-1782 send correct content language on exit link events
  godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Features/ToolTraining/ToolTrainingViewModel.swift
  godtools/App/Services/Analytics/AnalyticsTracking/ExitLinkAnalytics.swift
  godtools/App/Services/Analytics/AnalyticsTracking/Models/ExitLinkModel.swift
  godtools/App/Services/Analytics/Firebase/FirebaseAnalytics.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Page/MobileContentPageViewModel.swift
  godtools/App/Share/Domain/UseCases/GetLanguageUseCase/GetLanguageUseCase.swift
  godtools/App/Share/Domain/UseCases/GetLanguageUseCase/LanguageDomainModel.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1342 GT 1785 updates for shared parser
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools/App/DependencyContainer/AppDataLayerDependencies.swift
  godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Features/ToolSettings/ToolSettings/ToolSettingsViewModel.swift
  godtools/App/Share/Data/TranslationsRepository/ManifestParser/ParseTranslationManifestForRelatedFiles.swift
  godtools/App/Share/Data/TranslationsRepository/ManifestParser/ParseTranslationManifestForRenderer.swift
  godtools/App/Share/Data/TranslationsRepository/ManifestParser/ParseTranslationManifestForTips.swift
  godtools/App/Share/Data/TranslationsRepository/ManifestParser/TranslationManifestParser.swift
  godtools/App/Share/Data/TranslationsRepository/ManifestParser/TranslationManifestParserType.swift
  godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesFilter.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1345 GT-tool-details-use-cases
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/ToolDetails/Domain/UseCases/GetToolDetailsMediaUseCase/GetToolDetailsMediaUseCase.swift
  godtools/App/Features/ToolDetails/Domain/UseCases/GetToolDetailsMediaUseCase/ToolDetailsMediaDomainModel.swift
  godtools/App/Features/ToolDetails/Domain/UseCases/GetToolVersionsUseCase/GetToolVersionsUseCase.swift
  godtools/App/Features/ToolDetails/Domain/UseCases/GetToolVersionsUseCase/ToolVersionDomainModel.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsAboutView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsMediaView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsPrimaryButtonsView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsSegmentType.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsTitleHeaderView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsToggleFavoriteButton.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsVersionsView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardViewModel.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsHostingView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1344 GT-1784 renderer analytics send contentLanguage for content events
  godtools/App/Services/Renderer/Analytics/MobileContentEventAnalyticsTracking.swift
Labels: Cru - Ready for Review

#1343 GT-1783 renderer analytics send content language for screen view events
  godtools/App/Services/Analytics/AnalyticsTracking/Models/TrackScreenModel.swift
  godtools/App/Services/Analytics/AnalyticsTracking/PageViewedAnalytics.swift
  godtools/App/Services/Renderer/Views/Lesson/Views/Page/LessonPageViewModel.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/CardCollectionPage/MobileContentCardCollectionPageViewModel.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentPage/MobileContentContentPageViewModel.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Card/ToolPageCardViewModel.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Page/ToolPageViewModel.swift
Labels: Cru - Ready for Review

#1346 GT-1786 remove device language class
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Menu/Menu/MenuViewModel.swift
  godtools/App/Features/Onboarding/Models/OnboardingTutorialCustomViewBuilder.swift
  godtools/App/Flows/Menu/MenuFlow.swift
  godtools/App/Flows/Tutorial/TutorialFlow.swift
  godtools/App/Flows/Tutorial/TutorialFlowDiContainer.swift
  godtools/App/Services/DeviceLanguage/DeviceLanguage.swift
  godtools/App/Share/Domain/UseCases/GetOptInOnboardingTutorialAvailableUseCase/GetOptInOnboardingTutorialAvailableUseCase.swift
  godtools/App/Share/Domain/UseCases/GetTutorialUseCase/GetTutorialUseCase.swift
Labels: Cru - Ready for Review, Feature - Refactor for Combine

#1349 GT-Moved LanguageSupportable on ResourceModel into separate file extension
  godtools.xcodeproj/project.pbxproj
  godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModel+LanguageSupportable.swift
  godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModel.swift
Labels: Cru - Ready for Review

#1350 GT-1413 delete resources after sync
  godtools/App/Features/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
  godtools/App/Features/Lessons/Lesson/LessonViewModel.swift
  godtools/App/Features/Tool/ToolViewModel.swift
  godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
  godtools/App/Flows/Lesson/LessonFlow.swift
  godtools/App/Flows/Tract/TractFlow.swift
  godtools/App/Services/Renderer/Navigation/MobileContentRendererNavigation.swift
  godtools/App/Services/Renderer/Renderer/MobileContentPageRenderer.swift
  godtools/App/Services/Renderer/Renderer/MobileContentRenderedPageContext.swift
  godtools/App/Services/Renderer/Renderer/MobileContentRendererLanguageTranslationManifest.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/Sync/RealmResourcesCacheSync.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
Labels: Cru - Ready for Review

#1348 GT-1743 get all tools use case
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
  godtools/App/AppDiContainer.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoriesView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoriesViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoryButtonView/ToolCategoryButtonState.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoryButtonView/ToolCategoryButtonView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoryButtonView/ViewModels/AllToolsCategoryButtonViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoryButtonView/ViewModels/BaseToolCategoryButtonViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoryButtonView/ViewModels/ToolCategoryButtonViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Services/Resources/ResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
  godtools/App/Share/Domain/Extensions/Array+ResourceModel.swift
  godtools/App/Share/Domain/UseCases/GetAllToolsUseCase/GetAllToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolCategoriesUseCase/GetToolCategoriesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolCategoriesUseCase/ToolCategoryDomainModel.swift
  godtools/App/Share/Domain/UseCases/GetToolCategoriesUseCase/ToolCategoryType.swift
Labels: Cru - Ready for Review

#1352 GT-1787 language settings feature
  godtools.xcodeproj/project.pbxproj
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/LanguageSettings/Domain/UseCases/GetSettingsLanguagesUseCase/GetSettingsLanguagesUseCase.swift
  godtools/App/Features/LanguageSettings/Domain/UseCases/GetSettingsParallelLanguageUseCase/GetSettingsParallelLanguageUseCase.swift
  godtools/App/Features/LanguageSettings/Domain/UseCases/GetSettingsPrimaryLanguageUseCase/GetSettingsPrimaryLanguageUseCase.swift
  godtools/App/Features/LanguageSettings/Domain/UseCases/UserDidDeleteSettingsParallelLanguageUseCase/UserDidDeleteSettingsParallelLanguageUseCase.swift
  godtools/App/Features/LanguageSettings/Domain/UseCases/UserDidSetSettingsParallelLanguageUseCase/UserDidSetSettingsParallelLanguageUseCase.swift
  godtools/App/Features/LanguageSettings/Domain/UseCases/UserDidSetSettingsPrimaryLanguageUseCase/UserDidSetSettingsPrimaryLanguageUseCase.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/ChooseLanguageView.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/ChooseLanguageView.xib
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/ChooseLanguageViewModel.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/ChooseLanguageViewModelType.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/Subviews/ChooseLanguageCell.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/Subviews/ChooseLanguageCell.xib
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/Subviews/ChooseLanguageCellViewModel.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/Subviews/ChooseLanguageCellViewModelType.swift
  godtools/App/Features/LanguageSettings/Presentation/LanguageSettings/LanguageSettingsView.swift
  godtools/App/Features/LanguageSettings/Presentation/LanguageSettings/LanguageSettingsView.xib
  godtools/App/Features/LanguageSettings/Presentation/LanguageSettings/LanguageSettingsViewModel.swift
  godtools/App/Features/LanguageSettings/Presentation/LanguageSettings/LanguageSettingsViewModelType.swift
  godtools/App/Features/SetupParallel/Views/ParallelLanguageListViewModel.swift
  godtools/App/Features/ToolSettings/LanguagesList/LanguagesListView.swift
  godtools/App/Features/ToolSettings/LanguagesList/LanguagesListViewModel.swift
  godtools/App/Features/ToolSettings/LanguagesList/Subviews/BaseLanguagesListItemViewModel.swift
  godtools/App/Features/ToolSettings/LanguagesList/Subviews/DeleteLanguageListItemViewModel.swift
  godtools/App/Features/ToolSettings/LanguagesList/Subviews/LanguagesListItemView.swift
  godtools/App/Features/ToolSettings/LanguagesList/Subviews/LanguagesListItemViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/LanguageSettings/LanguageSettingsFlow.swift
Labels: Cru - Ready for Review

#1353 GT Moved FavoritingToolMessageCache
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/DependencyContainer/AppDataLayerDependencies.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Share/Data/FavoritingToolMessageCache/FavoritingToolMessageCache.swift
Labels: Cru - Ready for Review

#1355 GT-Upgrade godtools shared parser version to 0.7.0-snapshot
  Podfile
  Podfile.lock
Labels: Cru - Ready for Review

#1360 GT-1717 remove downloaded language logic and green arrow icon from language settings
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/ChooseLanguageViewModel.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/Subviews/ChooseLanguageCell.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/Subviews/ChooseLanguageCell.xib
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/Subviews/ChooseLanguageCellViewModel.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/Subviews/ChooseLanguageCellViewModelType.swift
  godtools/App/Features/SetupParallel/Views/ParallelLanguageListViewModel.swift
  godtools/App/Flows/LanguageSettings/LanguageSettingsFlow.swift
  godtools/App/Services/DownloadedLanguages/DownloadedLanguagesCache.swift
  godtools/App/Services/DownloadedLanguages/Models/DownloadedLanguageModel.swift
  godtools/App/Services/DownloadedLanguages/Models/DownloadedLanguageModelType.swift
  godtools/App/Services/DownloadedLanguages/Models/RealmDownloadedLanguage.swift
  godtools/App/Services/RealmDatabase/RealmDatabase.swift
  godtools/Assets.xcassets/download_green.imageset/Contents.json
  godtools/Assets.xcassets/download_green.imageset/download_green.png
  godtools/Assets.xcassets/download_green.imageset/download_green@2x.png
  godtools/Assets.xcassets/download_green.imageset/download_green@3x.png
Labels: Cru - Ready for Review

#1361 GT-1494 navigate to lessons list after viewing a lesson.
  godtools/App/Flows/App/AppFlow.swift
Labels: Cru - Ready for Review

#1362 GT-1547 Send firebase event iam_tools
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
Labels: Cru - Ready for Review

#1366 GT-1682 Fix shareable image sizing
  godtools/App/Features/ToolSettings/ToolSettings/Subviews/ToolSettingsShareables/ToolSettingsShareableItemView.swift
Labels: Cru - Ready for Review

#1367 GT-1720 Remove GodTools navigation title from tool
  godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarViewModel.swift
  godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarViewModelType.swift
Labels: Cru - Ready for Review

#1354 GT-1745 get all favorited tools use case
  godtools.xcodeproj/project.pbxproj
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardNavButtonView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardVerticalTextView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/FavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/Subviews/NoFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/FavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Services/Localization/LocalizationServices.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedResourceModelsUseCase/GetAllFavoritedResourceModelsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsLatestTranslationFilesUseCase/GetAllFavoritedToolsLatestTranslationFilesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsUseCase/GetAllFavoritedToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetAllToolsUseCase/GetAllToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/GetShortcutItemsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetSpotlightToolsUseCase/GetSpotlightToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolCategoriesUseCase/GetToolCategoriesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolUseCase/GetToolUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolUseCase/ToolDomainModel.swift
  godtools/App/Share/Extensions/LayoutDirection+LanguageDirection.swift
Labels: Cru - Ready for Review

#1368 remove youtube pod and install as a swift package
  Podfile
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
  godtools/App/Features/Onboarding/Views/OnboardingTutorialIntroView.swift
  godtools/App/Features/ToolSettings/ShareToolScreenTutorial/ShareToolScreenTutorialView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentEmbeddedVideo/MobileContentEmbeddedVideoView.swift
  godtools/App/Share/SwiftUI Views/VideoView/VideoView.swift
  godtools/App/Share/SwiftUI Views/VideoView/VideoViewCoordinator.swift
  godtools/App/Share/Views/TutorialCell/TutorialCell.swift
  godtools/App/Share/Views/TutorialPagerView/TutorialPagerView.swift
  godtools/App/Share/Views/VideoPlayerView/VideoPlayerView.swift
Labels: Cru - Ready for Review

#1370 GT upgrade Github Actions to Xcode_14.0
  .github/workflows/build.yml
  .github/workflows/download_onesky_translations.yml
Labels: Cru - Ready for Review

#1372 GT-1120 Add support for bold and underline on content text elements in renderer
  godtools.xcodeproj/project.pbxproj
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextViewModel.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextViewModelType.swift
  godtools/App/Share/Extensions/UILabel+Underline.swift
Labels: Cru - Ready for Review

#1373 GT-1594 Darken tool menu text
  godtools/App/Features/Tools/ToolsMenu/Views/ToolsMenuToolbar/Views/ToolsMenuToolbarItemView.swift
Labels: Cru - Ready for Review

#1377 GT-1715 sort favorited resources by language availability
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsUseCase/GetAllFavoritedToolsUseCase.swift
Labels: Cru - Ready for Review

#1364 GT-1748 get lessons use case
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Lessons/Lessons/LessonsContentView.swift
  godtools/App/Features/Lessons/Lessons/LessonsContentViewModel.swift
  godtools/App/Features/Lessons/Lessons/LessonsListView/LessonsListView.swift
  godtools/App/Features/Lessons/Lessons/LessonsListView/LessonsListViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardNavButtonView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardVerticalTextView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/ToolSpotlightView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/ViewModels/ToolSpotlightViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/FavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/Subviews/NoFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/FavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/FlowStep.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
  godtools/App/Share/Domain/UseCases/GetLanguageAvailabilityUseCase/GetLanguageAvailablityUseCase.swift
  godtools/App/Share/Domain/UseCases/GetLanguageAvailabilityUseCase/LanguageAvailabilityDomainModel.swift
  godtools/App/Share/Domain/UseCases/GetLessonUseCase/GetLessonUseCase.swift
  godtools/App/Share/Domain/UseCases/GetLessonUseCase/LessonDomainModel.swift
  godtools/App/Share/Domain/UseCases/GetLessonsUseCase/GetLessonsUseCase.swift
  godtools/App/Share/Domain/ViewModels/LessonCardProvider.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/LessonCardView.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/LessonCardViewModel.swift
  godtools/App/Share/SwiftUI Views/LessonCardsView/LessonCardsView.swift
  godtools/App/Share/SwiftUI Views/ToolCardsCarouselView/ToolCardsCarouselView.swift
Labels: Cru - Ready for Review

#1374 GT-1544 Fix openers back to home
  godtools/App/Flows/App/AppFlow.swift
Labels: Cru - Ready for Review

#1379 GT-1798 Fix bug where lesson would sometimes open in the parallel language (Spanish)
  Podfile.lock
  godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
Labels: Cru - Ready for Review

#1376 GT-1744 get recommended lessons use case
  godtools.xcodeproj/project.pbxproj
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/FavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/Subviews/NoFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/FavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
  godtools/App/Share/Domain/UseCases/GetFeaturedLessonsUseCase/GetFeaturedLessonsUseCase.swift
  godtools/App/Share/SwiftUI Views/LessonCardsView/LessonCardsView.swift
Labels: Cru - Ready for Review

#1381 Merge develop into master for new QA release
  .github/workflows/build.yml
  Gemfile.lock
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Lessons/Lessons/LessonsContentView.swift
  godtools/App/Features/Lessons/Lessons/LessonsContentViewModel.swift
  godtools/App/Features/Lessons/Lessons/LessonsListView/LessonsListView.swift
  godtools/App/Features/Lessons/Lessons/LessonsListView/LessonsListViewModel.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsMediaView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardNavButtonView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardVerticalTextView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ToolCardView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/ToolSpotlightView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/ViewModels/ToolSpotlightViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/FavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/Subviews/NoFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/FavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/FlowStep.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
  godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsUseCase/GetAllFavoritedToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetFeaturedLessonsUseCase/GetFeaturedLessonsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetLanguageAvailabilityUseCase/GetLanguageAvailablityUseCase.swift
  godtools/App/Share/Domain/UseCases/GetLanguageAvailabilityUseCase/LanguageAvailabilityDomainModel.swift
  godtools/App/Share/Domain/UseCases/GetLessonUseCase/GetLessonUseCase.swift
  godtools/App/Share/Domain/UseCases/GetLessonUseCase/LessonDomainModel.swift
  godtools/App/Share/Domain/UseCases/GetLessonsUseCase/GetLessonsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
  godtools/App/Share/Domain/ViewModels/LessonCardProvider.swift
  godtools/App/Share/SwiftUI Views/AnimatedSwiftUIView/AnimatedSwiftUIView.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/LessonCardView.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/LessonCardViewModel.swift
  godtools/App/Share/SwiftUI Views/LessonCardsView/LessonCardsView.swift
  godtools/App/Share/SwiftUI Views/ToolCardsCarouselView/ToolCardsCarouselView.swift
Labels: Release - Version 6.0.3

#1383 GT-1747 lessons refactoring
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Lessons/Lessons/LessonsHostingView.swift
  godtools/App/Features/Lessons/Lessons/LessonsListView/LessonsListView.swift
  godtools/App/Features/Lessons/Lessons/LessonsListView/LessonsListViewModel.swift
  godtools/App/Features/Lessons/Lessons/LessonsView/LessonsView.swift
  godtools/App/Features/Lessons/Lessons/LessonsView/LessonsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuView.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModelType.swift
  godtools/App/Share/Domain/ViewModels/LessonCardProvider.swift
Labels: Cru - Ready for Review

#1384 GT add SwiftUI Image to ImageCatalog
  godtools/App/Features/Articles/ArticlesWeb/ArticleWebView.swift
  godtools/App/Features/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
  godtools/App/Features/DownloadTool/DownloadTool/DownloadToolView.swift
  godtools/App/Features/LearnToShareTool/LearnToShareToolView.swift
  godtools/App/Features/Lessons/Lesson/LessonView.swift
  godtools/App/Features/Menu/Tutorial/TutorialView.swift
  godtools/App/Features/Onboarding/Views/OnboardingTutorialIntroView.swift
  godtools/App/Features/Onboarding/Views/OnboardingTutorialIntroViewModel.swift
  godtools/App/Features/Tool/Models/ToolBackButtonImageType+Image.swift
  godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarView.swift
  godtools/App/Features/ToolSettings/ShareToolScreenTutorial/ShareToolScreenTutorialView.swift
  godtools/App/Features/ToolTraining/ToolTrainingViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuView.swift
  godtools/App/Features/Tools/ToolsMenu/Views/ToolsMenuToolbar/ToolsMenuToolbarViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/CardCollectionPage/MobileContentCardCollectionPageView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.swift
  godtools/App/Services/Renderer/Views/Tool/Views/CallToAction/ToolPageCallToActionViewModel.swift
  godtools/App/Share/Extensions/UIViewController+NavBackItem.swift
  godtools/App/Share/ImageCatalog.swift
  godtools/App/Share/Views/LoadingView/LoadingView.swift
  godtools/App/Share/Views/VideoPlayerView/VideoPlayerView.swift
Labels: Cru - Ready for Review

#1386 GT-1804 restore button to delete parallel language
  Podfile.lock
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/ChooseLanguageViewModel.swift
Labels: Cru - Ready for Review, Release - Version 6.0.3

#1388 GT-1805 missing headers
  Podfile.lock
  godtools/App/Features/Lessons/Lessons/LessonsView/LessonsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoriesViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/FavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsViewModel.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/LessonCardViewModel.swift
Labels: Cru - Ready for Review, Release - Version 6.0.3

#1390 GT-1806 fix duplicate back button on all favorites
  Podfile.lock
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
Labels: Cru - Ready for Review, Release - Version 6.0.3

#1394 Merge develop into master for new QA release
  .github/workflows/build.yml
  Gemfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Articles/ArticlesWeb/ArticleWebView.swift
  godtools/App/Features/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
  godtools/App/Features/DownloadTool/DownloadTool/DownloadToolView.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/ChooseLanguageViewModel.swift
  godtools/App/Features/LearnToShareTool/LearnToShareToolView.swift
  godtools/App/Features/Lessons/Lesson/LessonView.swift
  godtools/App/Features/Lessons/Lessons/LessonsHostingView.swift
  godtools/App/Features/Lessons/Lessons/LessonsListView/LessonsListView.swift
  godtools/App/Features/Lessons/Lessons/LessonsListView/LessonsListViewModel.swift
  godtools/App/Features/Lessons/Lessons/LessonsView/LessonsView.swift
  godtools/App/Features/Lessons/Lessons/LessonsView/LessonsViewModel.swift
  godtools/App/Features/Menu/Tutorial/TutorialView.swift
  godtools/App/Features/Onboarding/Views/OnboardingTutorialIntroView.swift
  godtools/App/Features/Onboarding/Views/OnboardingTutorialIntroViewModel.swift
  godtools/App/Features/Tool/Models/ToolBackButtonImageType+Image.swift
  godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarView.swift
  godtools/App/Features/ToolSettings/ShareToolScreenTutorial/ShareToolScreenTutorialView.swift
  godtools/App/Features/ToolTraining/ToolTrainingViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoriesViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/FavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuView.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuViewModelType.swift
  godtools/App/Features/Tools/ToolsMenu/Views/ToolsMenuToolbar/ToolsMenuToolbarViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/CardCollectionPage/MobileContentCardCollectionPageView.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.swift
  godtools/App/Services/Renderer/Views/Tool/Views/CallToAction/ToolPageCallToActionViewModel.swift
  godtools/App/Share/Domain/ViewModels/LessonCardProvider.swift
  godtools/App/Share/Extensions/UIViewController+NavBackItem.swift
  godtools/App/Share/ImageCatalog.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/LessonCardViewModel.swift
  godtools/App/Share/Views/LoadingView/LoadingView.swift
  godtools/App/Share/Views/VideoPlayerView/VideoPlayerView.swift
Labels: Cru - Ready for Review, Release - Version 6.0.3

#1392 GT remove okta auth protocols
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/Features/Menu/Account/AccountViewModel.swift
  godtools/App/Features/Menu/Menu/MenuViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/Menu/MenuFlow.swift
  godtools/App/Services/Analytics/Firebase/FirebaseAnalytics.swift
  godtools/App/Services/Analytics/Snowplow/SnowplowAnalytics.swift
  godtools/App/Services/EmailSignUp/EmailSignUpService.swift
  godtools/App/Services/UserAuthentication/Models/AuthUserModelType.swift
  godtools/App/Services/UserAuthentication/UserAuthenticationType.swift
  godtools/App/Share/Data/OktaUserAuthentication/OktaAuthUserModel.swift
  godtools/App/Share/Data/OktaUserAuthentication/OktaAuthenticationConfiguration.swift
  godtools/App/Share/Data/OktaUserAuthentication/OktaUserAuthentication.swift
Labels: Cru - Ready for Review

#1396 GT-1494 Fix closing lesson to lessons list from deep link
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuView.swift
  godtools/App/Flows/App/AppFlow.swift
Labels: Cru - Ready for Review, Release - Version 6.0.3

#1397 GT-1809 Fix back button disappearing in iOS 14
  godtools.xcodeproj/project.pbxproj
  godtools/App/Features/Articles/ArticlesWeb/ArticleWebView.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/ChooseLanguageView.swift
  godtools/App/Features/LearnToShareTool/LearnToShareToolView.swift
  godtools/App/Features/Menu/Tutorial/TutorialView.swift
  godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsHostingView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Features/ToolSettings/ShareToolScreenTutorial/ShareToolScreenTutorialView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsHostingView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuView.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Share/Extensions/UIViewController+NavBackItem.swift
  godtools/App/Share/Extensions/UIViewController+NavItem.swift
  godtools/App/Share/Views/LoadingView/LoadingView.swift
  godtools/App/Share/Views/TutorialPagerView/TutorialPagerView.swift
Labels: Cru - Ready for Review, Release - Version 6.0.3

#1387 GT-1789 remove get all favorited resource models use case
  godtools.xcodeproj/project.pbxproj
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedResourceModelsUseCase/GetAllFavoritedResourceModelsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsLatestTranslationFilesUseCase/GetAllFavoritedToolsLatestTranslationFilesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsUseCase/GetAllFavoritedToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/GetShortcutItemsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/ToolShortcutItem.swift
Labels: Cru - Ready for Review

#1389 GT-1731 Category Button Sizing
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoryButtonView/ToolCategoryButtonView.swift
Labels: Cru - Ready for Review

#1400 Merge develop into master for new QA release
  Podfile
  Podfile.lock
  godtools.xcodeproj/project.pbxproj
  godtools/App/AppDiContainer.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Articles/ArticlesWeb/ArticleWebView.swift
  godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/ChooseLanguageView.swift
  godtools/App/Features/LearnToShareTool/LearnToShareToolView.swift
  godtools/App/Features/Menu/Account/AccountViewModel.swift
  godtools/App/Features/Menu/Menu/MenuViewModel.swift
  godtools/App/Features/Menu/Tutorial/TutorialView.swift
  godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsHostingView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Features/ToolSettings/ShareToolScreenTutorial/ShareToolScreenTutorialView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoryButtonView/ToolCategoryButtonView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsHostingView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/ToolsMenu/ToolsMenuView.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/Menu/MenuFlow.swift
  godtools/App/Services/Analytics/Firebase/FirebaseAnalytics.swift
  godtools/App/Services/Analytics/Snowplow/SnowplowAnalytics.swift
  godtools/App/Services/EmailSignUp/EmailSignUpService.swift
  godtools/App/Services/UserAuthentication/Models/AuthUserModelType.swift
  godtools/App/Services/UserAuthentication/UserAuthenticationType.swift
  godtools/App/Share/Data/OktaUserAuthentication/OktaAuthUserModel.swift
  godtools/App/Share/Data/OktaUserAuthentication/OktaAuthenticationConfiguration.swift
  godtools/App/Share/Data/OktaUserAuthentication/OktaUserAuthentication.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedResourceModelsUseCase/GetAllFavoritedResourceModelsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsLatestTranslationFilesUseCase/GetAllFavoritedToolsLatestTranslationFilesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsUseCase/GetAllFavoritedToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/GetShortcutItemsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/ToolShortcutItem.swift
  godtools/App/Share/Extensions/UIViewController+NavBackItem.swift
  godtools/App/Share/Extensions/UIViewController+NavItem.swift
  godtools/App/Share/Views/LoadingView/LoadingView.swift
  godtools/App/Share/Views/TutorialPagerView/TutorialPagerView.swift
Labels: Release - Version 6.0.3

#1393 GT-1480 Removed check here for not FollowUp event
  godtools/App/Services/Renderer/Views/Tool/Views/Modal/ToolPageModalView.swift
Labels: Cru - Ready for Review, Release - Version 6.0.3

#1401 GT-1141 Update training tip ask icon to fix clipping at bottom of icon
  godtools/Assets.xcassets/Features/Tool/TrainingTips/training_tip_ask_filled_red.imageset/training_tip_ask_filled_red.png
  godtools/Assets.xcassets/Features/Tool/TrainingTips/training_tip_ask_filled_red.imageset/training_tip_ask_filled_red@2x.png
  godtools/Assets.xcassets/Features/Tool/TrainingTips/training_tip_ask_filled_red.imageset/training_tip_ask_filled_red@3x.png
Labels: WIP, Release - Version 6.0.3

#1395 GT-1768 Jumpy Home Screen
  godtools/App/Features/Lessons/Lessons/LessonsView/LessonsView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/FavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsViewModel.swift
  godtools/App/Share/Domain/UseCases/GetLanguageUseCase/LanguageDomainModel.swift
  godtools/App/Share/Domain/UseCases/GetLessonUseCase/LessonDomainModel.swift
  godtools/App/Share/Domain/UseCases/GetToolUseCase/ToolDomainModel.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/LessonCardView.swift
  godtools/App/Share/SwiftUI Views/ToolCardsCarouselView/ToolCardsCarouselView.swift
Labels: Cru - Ready for Review

#1402 GT-1642 Create 2 phrases for "About" text
  godtools/App/Features/Menu/About/AboutViewModel.swift
  godtools/App/Features/Menu/Menu/MenuViewModel.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
  godtools/Base.lproj/Localizable.strings
Labels: Cru - Ready for Review

#1399 GT-1810 persist at least one tool translation and related files
  godtools.xcodeproj/project.pbxproj
  godtools/App/DependencyContainer/AppDataLayerDependencies.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/ToolDetails/Domain/UseCases/GetToolVersionsUseCase/GetToolVersionsUseCase.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/ToolNavigation/ToolNavigationFlow.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
  godtools/App/Services/RealmDatabase/RealmDatabase.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
  godtools/App/Share/Data/LanguagesRepository/Cache/RealmLanguagesCache.swift
  godtools/App/Share/Data/LanguagesRepository/Cache/Sync/RealmLanguagesCacheSync.swift
  godtools/App/Share/Data/LanguagesRepository/Cache/Sync/RealmLanguagesCacheSyncResult.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/Sync/RealmResourcesCacheSync.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/Sync/RealmResourcesCacheSyncResult.swift
  godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
  godtools/App/Share/Data/TrackDownloadedTranslationsRepository/Cache/Models/RealmDownloadedTranslation.swift
  godtools/App/Share/Data/TrackDownloadedTranslationsRepository/Cache/TrackDownloadedTranslationsCache.swift
  godtools/App/Share/Data/TrackDownloadedTranslationsRepository/DownloadedTranslationDataModel.swift
  godtools/App/Share/Data/TrackDownloadedTranslationsRepository/DownloadedTranslationDataModelType.swift
  godtools/App/Share/Data/TrackDownloadedTranslationsRepository/TrackDownloadedTranslationsRepository.swift
  godtools/App/Share/Data/TranslationsRepository/Cache/RealmTranslationsCache.swift
  godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsLatestTranslationFilesUseCase/GetAllFavoritedToolsLatestTranslationFilesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsUseCase/GetAllFavoritedToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/GetShortcutItemsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/ToolShortcutItem.swift
  godtools/App/Share/Domain/UseCases/GetToolCategoriesUseCase/GetToolCategoriesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/DetermineToolTranslationsToDownload/DetermineDeepLinkedToolTranslationsToDownload.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/DetermineToolTranslationsToDownload/DetermineToolTranslationsToDownload.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolUseCase/GetToolUseCase.swift
Labels: Cru - Ready for Review, Release - Version 6.0.3

#1403 Merge develop into master for new QA release
  godtools.xcodeproj/project.pbxproj
  godtools/App/DependencyContainer/AppDataLayerDependencies.swift
  godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
  godtools/App/Features/Lessons/Lessons/LessonsView/LessonsView.swift
  godtools/App/Features/Menu/About/AboutViewModel.swift
  godtools/App/Features/Menu/Menu/MenuViewModel.swift
  godtools/App/Features/ToolDetails/Domain/UseCases/GetToolVersionsUseCase/GetToolVersionsUseCase.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsView.swift
  godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
  godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/FavoriteToolsView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentView.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
  godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsViewModel.swift
  godtools/App/Flows/App/AppFlow.swift
  godtools/App/Flows/ToolNavigation/ToolNavigationFlow.swift
  godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
  godtools/App/Services/RealmDatabase/RealmDatabase.swift
  godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
  godtools/App/Services/Renderer/Views/Tool/Views/Modal/ToolPageModalView.swift
  godtools/App/Share/Data/LanguagesRepository/Cache/RealmLanguagesCache.swift
  godtools/App/Share/Data/LanguagesRepository/Cache/Sync/RealmLanguagesCacheSync.swift
  godtools/App/Share/Data/LanguagesRepository/Cache/Sync/RealmLanguagesCacheSyncResult.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/Sync/RealmResourcesCacheSync.swift
  godtools/App/Share/Data/ResourcesRepository/Cache/Sync/RealmResourcesCacheSyncResult.swift
  godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
  godtools/App/Share/Data/TrackDownloadedTranslationsRepository/Cache/Models/RealmDownloadedTranslation.swift
  godtools/App/Share/Data/TrackDownloadedTranslationsRepository/Cache/TrackDownloadedTranslationsCache.swift
  godtools/App/Share/Data/TrackDownloadedTranslationsRepository/DownloadedTranslationDataModel.swift
  godtools/App/Share/Data/TrackDownloadedTranslationsRepository/DownloadedTranslationDataModelType.swift
  godtools/App/Share/Data/TrackDownloadedTranslationsRepository/TrackDownloadedTranslationsRepository.swift
  godtools/App/Share/Data/TranslationsRepository/Cache/RealmTranslationsCache.swift
  godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsLatestTranslationFilesUseCase/GetAllFavoritedToolsLatestTranslationFilesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsUseCase/GetAllFavoritedToolsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetDeviceLanguageUseCase/DeviceLanguageDomainModel.swift
  godtools/App/Share/Domain/UseCases/GetDeviceLanguageUseCase/GetDeviceLanguageUseCase.swift
  godtools/App/Share/Domain/UseCases/GetLanguageUseCase/GetLanguageUseCase.swift
  godtools/App/Share/Domain/UseCases/GetLanguageUseCase/LanguageDomainModel.swift
  godtools/App/Share/Domain/UseCases/GetLessonUseCase/LessonDomainModel.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/GetShortcutItemsUseCase.swift
  godtools/App/Share/Domain/UseCases/GetShortcutItemsUseCase/ToolShortcutItem.swift
  godtools/App/Share/Domain/UseCases/GetToolCategoriesUseCase/GetToolCategoriesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/DetermineToolTranslationsToDownload/DetermineDeepLinkedToolTranslationsToDownload.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/DetermineToolTranslationsToDownload/DetermineToolTranslationsToDownload.swift
  godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolUseCase/GetToolUseCase.swift
  godtools/App/Share/Domain/UseCases/GetToolUseCase/ToolDomainModel.swift
  godtools/App/Share/SwiftUI Views/LessonCardView/LessonCardView.swift
  godtools/App/Share/SwiftUI Views/ToolCardsCarouselView/ToolCardsCarouselView.swift
  godtools/Assets.xcassets/Features/Tool/TrainingTips/training_tip_ask_filled_red.imageset/training_tip_ask_filled_red.png
  godtools/Assets.xcassets/Features/Tool/TrainingTips/training_tip_ask_filled_red.imageset/training_tip_ask_filled_red@2x.png
  godtools/Assets.xcassets/Features/Tool/TrainingTips/training_tip_ask_filled_red.imageset/training_tip_ask_filled_red@3x.png
  godtools/Base.lproj/Localizable.strings
Labels: Release - Version 6.0.3
